include(GoogleTest)

function(add_db_test TEST_NAME TEST_FILE)
    add_executable(${TEST_NAME} ${TEST_FILE})
    target_link_libraries(${TEST_NAME} PRIVATE GTest::gtest_main db_engine_lib)
    gtest_discover_tests(${TEST_NAME})
endfunction()

add_db_test(PagerTests test_pager.cpp)
add_db_test(RecordManagerTests test_record_manager.cpp)
add_db_test(BufferPoolTests test_buffer_pool.cpp)
add_db_test(StringPoolTests test_string_pool.cpp)
add_db_test(ParserTests test_parser.cpp)
add_db_test(LexerTests test_lexer.cpp)
add_db_test(LoggerTests test_logger.cpp)
add_db_test(ConsoleTests test_console.cpp)
add_db_test(IndexTests b_star_plus_tree_tests.cpp)